### ISSUE TITLE
Image loading becomes unreliable if multiple files (image and non-image) with different extensions present

### ISSUE THREAD

**Issue by porkness** [Ancurio/mkxp#101]
For example, this is how my RMVXAce RTP's Tilesets folder looks like:
```
Dungeon_A1.png
Dungeon_A1.txt
Dungeon_A2.png
Dungeon_A2.txt
...
```
Instead of loading the png file, MKXP is trying to load the txt file and then complains "format not supported"

**Comment by Ancurio** [comment]
Sorry for the delay.
