### ISSUE TITLE
Build Instruction for absolute beginners

### ISSUE THREAD

**Issue by Xenovo** [Ancurio/mkxp#104]
Can someone give compile instructions for an absolute Linux beginner (like me)? I've worked in windows and I can possibly use the binaries, but I need to hack the source a bit (I can do that, but not work around the boring Linux ways). It'll be good to have a step-by-step guide for this.

**Comment by Ancurio** [comment]
For what operating system?

**Comment by Xenovo** [comment]
For Linux (Ubuntu for a start). Sorry, forgot to mention.

**Comment by sorlok** [comment]
I've been working on a build guide:
https://docs.google.com/document/d/1xBHq2qccczn1ZcG4uc3DDGHhK0YxfmxI9TNRqjBLzFw

Please note that this is very rough around the edges, and that I haven't tested it on a clean install yet. (I'll probably have it done next weekend.) But do post back if you run into any issues and I'll use it to clarify the guide.

**Comment by Ancurio** [comment]
@sorlok You note that you're skipping the F1 menu bugfix in SDL2, in which case you probably don't need latest hg, 2.0.4 should be fine. Also I don't believe you need to compile SDL2_image and SDL2_ttf from source. For building the ruby shared library, passing `--enable-shared` to the configure script should do the trick (not really sure why it's disabled by default..).

**Comment by sorlok** [comment]
@Ancurio  Thanks for the information! I'll incorporate it into the build guide.

**Comment by Ancurio** [comment]
I've attempted to create a compact "dependency kit" containing all libraries/headers required to compile mkxp on a bare-bones Ubuntu 12.04 64bit installation. It includes a readme describing how to set it up: https://www.dropbox.com/s/mtp44ur367m2zts/mkxp-depkit.tar.xz?dl=0

@sorlok Maybe you want to try this out? Although you probably don't need it. It's good if you just want to hack on mkxp a bit, but probably isn't too helpful if you want to fully deploy a game with 32/64 builds etc. But maybe it'll still be handy for someone.

**Comment by sorlok** [comment]
@Ancurio Sure, I'll have a look. (FYI, I still plan on completing my own guide, including a section on cross-compiling. Like you said, for deployment.)

@Xenovo Could you also try out Ancurio's dependency kit? It might be easier to start with that while I tidy up my own install guide, and it should be sufficient just for hacking.

**Comment by sorlok** [comment]
@Xenovo I've fully tested my build guide on a new virtual machine. I also added a section on distribution. Should be good to go!

@Ancurio I added a link to the "dependency kit" in my build instructions. I also tried the "--enable-shared" flag for Ruby, but had some problems with it. I think I'm happy statically linking ruby in though, so no need to further debug this.

**Comment by Xenovo** [comment]
@sorlok, thanks :) Will try to compile it at the earliest when I get the time.

**Comment by TomTheDragon** [comment]
Is there a updated guide to this? I already tried the guide and also the dependency kit but both dont seem to work on more modern Ubuntu 16.04 64bit. My terminal just gets flooded with error messages basied around sigc++.

**Comment by Ancurio** [comment]
@TomTheDragon I think `-D_GLIBCXX_USE_CXX11_ABI=0` needs to be added to defines, on modern Fedora at least. I will try and update the depkit after exams.

**Comment by TomTheDragon** [comment]
@Ancurio
That seems to fixed at least most of the errors when using the dependency kit, the log looks now like this:

[  1%] Generating XXD for assets/icon.png
[  2%] Generating XXD for shader/common.h
[  3%] Generating XXD for shader/transSimple.frag
[  4%] Generating XXD for shader/trans.frag
[  5%] Generating XXD for shader/hue.frag
[  6%] Generating XXD for shader/sprite.frag
[  7%] Generating XXD for shader/plane.frag
[  9%] Generating XXD for shader/gray.frag
[ 10%] Generating XXD for shader/bitmapBlit.frag
[ 11%] Generating XXD for shader/flatColor.frag
[ 12%] Generating XXD for shader/simple.frag
[ 13%] Generating XXD for shader/simpleColor.frag
[ 14%] Generating XXD for shader/simpleAlpha.frag
[ 15%] Generating XXD for shader/simpleAlphaUni.frag
[ 17%] Generating XXD for shader/flashMap.frag
[ 18%] Generating XXD for shader/minimal.vert
[ 19%] Generating XXD for shader/simple.vert
[ 20%] Generating XXD for shader/simpleColor.vert
[ 21%] Generating XXD for shader/sprite.vert
[ 22%] Generating XXD for shader/tilemap.vert
[ 23%] Generating XXD for shader/tilemapvx.vert
[ 25%] Generating XXD for shader/blur.frag
[ 26%] Generating XXD for shader/blurH.vert
[ 27%] Generating XXD for shader/blurV.vert
[ 28%] Generating XXD for shader/simpleMatrix.vert
[ 29%] Generating XXD for assets/liberation.ttf
Scanning dependencies of target mkxp
[ 30%] Building CXX object CMakeFiles/mkxp.dir/src/main.cpp.o
[ 31%] Building CXX object CMakeFiles/mkxp.dir/src/audio.cpp.o
[ 32%] Building CXX object CMakeFiles/mkxp.dir/src/bitmap.cpp.o
[ 34%] Building CXX object CMakeFiles/mkxp.dir/src/eventthread.cpp.o
[ 35%] Building CXX object CMakeFiles/mkxp.dir/src/filesystem.cpp.o
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:401:8: error: ‘PHYSFS_EnumerateCallbackResult’ does not name a type
 static PHYSFS_EnumerateCallbackResult
        ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp: In member function ‘void FileSystem::createPathCache()’:
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:452:23: error: ‘cacheEnumCB’ was not declared in this scope
  PHYSFS_enumerate("", cacheEnumCB, &data);
                       ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:452:41: error: ‘PHYSFS_enumerate’ was not declared in this scope
  PHYSFS_enumerate("", cacheEnumCB, &data);
                                         ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp: At global scope:
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:463:8: error: ‘PHYSFS_EnumerateCallbackResult’ does not name a type
 static PHYSFS_EnumerateCallbackResult
        ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:504:8: error: ‘PHYSFS_EnumerateCallbackResult’ does not name a type
 static PHYSFS_EnumerateCallbackResult
        ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp: In member function ‘void FileSystem::initFontSets(SharedFontState&)’:
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:526:23: error: ‘findFontsFolderCB’ was not declared in this scope
  PHYSFS_enumerate("", findFontsFolderCB, &d);
                       ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:526:44: error: ‘PHYSFS_enumerate’ was not declared in this scope
  PHYSFS_enumerate("", findFontsFolderCB, &d);
                                            ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp: At global scope:
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:559:8: error: ‘PHYSFS_EnumerateCallbackResult’ does not name a type
 static PHYSFS_EnumerateCallbackResult
        ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp: In member function ‘void FileSystem::openRead(FileSystem::OpenHandler&, const char*)’:
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:659:50: error: ‘openReadEnumCB’ was not declared in this scope
    openReadEnumCB(&data, dir, fileList[i].c_str());
                                                  ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:663:25: error: ‘openReadEnumCB’ was not declared in this scope
   PHYSFS_enumerate(dir, openReadEnumCB, &data);
                         ^
/home/tom/Desktop/mkxp/mkxp/src/filesystem.cpp:663:46: error: ‘PHYSFS_enumerate’ was not declared in this scope
   PHYSFS_enumerate(dir, openReadEnumCB, &data);
                                              ^
CMakeFiles/mkxp.dir/build.make:262: die Regel für Ziel „CMakeFiles/mkxp.dir/src/filesystem.cpp.o“ scheiterte
make[2]: *** [CMakeFiles/mkxp.dir/src/filesystem.cpp.o] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/mkxp.dir/all“ scheiterte
make[1]: *** [CMakeFiles/mkxp.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by Ancurio** [comment]
@TomTheDragon physfs in the depkit is out of date. I'll fix it after exams.

**Comment by Ancurio** [comment]
Please reopen if the issue persists.
