### ISSUE TITLE
Run shell commands

### ISSUE THREAD

**Issue by Xenovo** [Ancurio/mkxp#105]
Can it be possible to hard code shell commands into an RMXP game, so they'll run in game time? What I mean is suppose after a certain event, a ruby script runs, which in turn runs a shell script in the Linux shell, and then gets the output to process it.

**Comment by cremno** [comment]
Isn't that just a basic Ruby question or am I misunderstanding you? See [`Kernel#``](http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-60), [`IO.popen`](http://ruby-doc.org/core-2.2.2/IO.html#method-c-popen), etc.

**Comment by Xenovo** [comment]
Does that work with mkxp too? Maybe I should have tried it before asking. Thanks for linking anyway!

**Comment by cremno** [comment]
It should work with mkxp as both are Ruby core methods.
