### ISSUE TITLE
Compilation patch (fixes eventthread errors)

### ISSUE THREAD

**Issue by sorlok** [Ancurio/mkxp#106]
The latest master fails to build, due to two problems:
* You include alext.h, but that relies on the macros AL_APIENTRY and ALC_APIENTRY, which are defined in al.h and alc.h. I added these includes before alext.h
* You have duplicate case statements for SDL_RENDER_DEVICE_RESET

The following patch fixes both:
```
From d06afb225eeb5b1b2499efa846ed6994c4110c4a Mon Sep 17 00:00:00 2001
From: "Seth N. Hetu" <seth.hetu@gmail.com>
Date: Mon, 25 May 2015 10:19:07 -0400
Subject: [PATCH 1/1] Compilation Fixes: alext.h doesn't include all needed
 macros. Also, remove duplicate switch case.

---
 src/eventthread.cpp | 5 ++---
 1 file changed, 2 insertions(+), 3 deletions(-)

diff --git a/src/eventthread.cpp b/src/eventthread.cpp
index 63a6d86..ad50ba1 100644
--- a/src/eventthread.cpp
+++ b/src/eventthread.cpp
@@ -28,6 +28,8 @@
 #include <SDL_thread.h>
 #include <SDL_touch.h>
 
+#include <al.h>
+#include <alc.h>
 #include <alext.h>
 
 #include "sharedstate.h"
@@ -492,9 +494,6 @@ int EventThread::eventFilter(void *data, SDL_Event *event)
 		Debug() << "****** SDL_RENDER_TARGETS_RESET";
 		return 0;
 
-	case SDL_RENDER_DEVICE_RESET :
-		Debug() << "****** SDL_RENDER_DEVICE_RESET";
-		return 0;
 	}
 
 	return 1;
-- 
1.9.1
```

**Comment by carstene1ns** [comment]
Under my system `alext.h` includes `al.h` and `alc.h` itself, so this is not needed. However, it will not hurt to do so as both have include guards. May I ask, which version of OpenAL you have installed?

About the duplicated switch case: Maybe you misread `SDL_RENDER_TARGETS_RESET` for `SDL_RENDER_DEVICE_RESET`? Or are they actually the same event?

**Comment by sorlok** [comment]
My version of OpenAL is listed as 1:1.14-4ubuntu1, which I assume means 1.14

Now that you  mention it, it does seem like I misread the switch statement. (Checks online)  ---ah, now I see: SDL_RENDER_DEVICE_RESET is new as of SDL 2.0.4, and I only have SDL 2.0.2 installed. My mistake on this one (although you might want to ifdef guard both cases, since they only print Debug information).

**Comment by Ancurio** [comment]
Your OpenAL issue is the same as #18, although in a different file, I will fix it the same way.

`SDL_RENDER_DEVICE_RESET` is a newly added value in SDL2, I didn't guard it because the README asks for latest hg SDL2 (and you should *really* use at least the latest stable release, ie. 2.0.4, if you don't want to chase the mercurial tip).

**Comment by Ancurio** [comment]
e4bc08e9725fac9e938c28b7ea4a5325dd713c59

**Comment by Ancurio** [comment]
e4bc08e9725fac9e938c28b7ea4a5325dd713c59

**Comment by sorlok** [comment]
@Ancurio The AL fix sounds good to me. Also, I'll update my SDL.
