### ISSUE TITLE
Default filename argument to Graphics.transition() should be "", not nil

### ISSUE THREAD

**Issue by sorlok** [Ancurio/mkxp#108]
The second argument to Graphics.transition() should default to "", not nil. (This represents using the default shader.) Currently, if someone wants to call Graphics.transition(8, "", 100), the "" will cause mkxp to try to load a Bitmap named "", rather than defaulting to the default shader. (Using nil instead of "" will work in MKXP, but not RPG Maker.)

Suggest changing line 719 of graphics.cpp:
```
//from:
Bitmap *transMap = filename ? new Bitmap(filename) : 0;

//to:
Bitmap *transMap = (filename && strlen(filename)>0) ? new Bitmap(filename) : 0;
```

**Comment by Ancurio** [comment]
I don't think using nil should have worked in mkxp because it will still try to parse it as a string from the ruby side.

**Comment by sorlok** [comment]
Makes sense, thanks.
