### ISSUE TITLE
fastBlit broken on some graphics cards

### ISSUE THREAD

**Issue by sorlok** [Ancurio/mkxp#114]
Bitmap::drawText() uses something called a "fastBlit" to draw text when that text is fully transparent and "un-tainted". This generally works fine, but on my Intel HD Graphics 4400 Integrated (a semi-cheap, but really-not-that-cheap graphics chip) on Linux, fast-blitted text has weird artifacts.

With fastBlit:
http://i.imgur.com/YnvgxnR.png

Without fastBlit (disabled in code):
http://i.imgur.com/838kTa7.png

The game in question is an RPG Maker VX new project with a single "Show Message Box" event. I've traced the calls on two different machines, and both are doing the right thing (in software). 

I'm happy to help track this down, but I'm worried it'll end up being shoddy drivers. Might be better just adding a compatibility option to disable fastBlit. 

*EDIT*: Ignore the different font between the two pictures; this issue also happened before I changed the font.

**Comment by Ancurio** [comment]
https://github.com/Ancurio/mkxp/blob/master/mkxp.conf.sample#L118

**Comment by sorlok** [comment]
Ah, that works, thanks!
