### ISSUE TITLE
Resolution multiplier

### ISSUE THREAD

**Issue by PabloNeirotti** [Ancurio/mkxp#120]
Hi there!

One of the features of my game I am wondering how to recreate in MKXP, is the ability to multiply the resolution.

I was using this Win32API reliant script:
http://forums.rpgmakerweb.com/index.php?/topic/14081-fullscreen/

Basically, through a hotkey, I enabled users to swap the game window size between 360p, 720p and 1280p. This will only stretch the game 360p resolution to a bigger Window. This is the intended behavior.

I was wondering if there was a way for me to manually set the Window width and height of the game (not the resolution: I need it fixed at 640x360).

Or maybe if there is a small piece of code that could be added to the C source to enable this behavior. I don't know C though :/

I'd appreciate any insights on this. Thank you!

**Comment by Ancurio** [comment]
It would be a very small change on the C++ side, but you'd have to either maintain your own compilation of mkxp, or stick to the same build forever.

**Comment by Ancurio** [comment]
Here is a patch that does what you want: http://pastebin.com/AhEhm95z

**Comment by PabloNeirotti** [comment]
Hey @Ancurio!

I was trying to do something like this but couldn't make it work. This did the job though! Thank you *very much* for this :). I don't mind staying off the master branch. If I ever need to upgrade, I can just re-apply this patch.

I understand the goal of the project is being a single solution to make RM projects cross platform. I am interested in that aspect but currently I am using it to extend the capabilities of RPG Maker. I love the font rendering, the performance. Thank you for all your dedication in making this project a reality.

Closing this now. Thank you, and have a nice day!
