### ISSUE TITLE
Set Fullscreen and Smooth Scaling within Ruby

### ISSUE THREAD

**Issue by PabloNeirotti** [Ancurio/mkxp#122]
Hi there!

I was wondering if there was a way to, from within Ruby, to make the game Fullscreen or not, or make it use the smoothScaling option or not.

There settings can be both defined in the config file (or Alt + Enter to toggle Fullscreen), but I want to provide this as part of the Settings menu.

I tried to do `Graphics.fullscreen = true` (innocent me!) to no luck. Don't know about smoothScaling.

Any clues?

Thank you!

**Comment by Ancurio** [comment]
> I tried to do Graphics.fullscreen = true (innocent me!) to no luck.

Hmm, that should have worked.

**Comment by PabloNeirotti** [comment]
Ok no, that is working in fact. I just forced it on every Scene update and worked (I guess one of my checks was overwritting it to false)

So that's a thing! Thanks! Now, can Smooth Scaling be controlled the same way with some method?

**Comment by Ancurio** [comment]
> So that's a thing! Thanks! Now, can Smooth Scaling be controlled the same way with some method?

Currently, no.
