### ISSUE TITLE
Black screen issues on various systems

### ISSUE THREAD

**Issue by PabloNeirotti** [Ancurio/mkxp#132]
Hi there!

So I pushed my game running MKXP live. Many are so happy to see the game performing so well. Your engine does wonders indeed!

However, GPU issues came along the way. I have several users reporting black screens, with logic and audio working fine in the background. 

Driver issues written all over the place. But this includes an Intel HD graphics user, to an nVidia GTX 760, latest drivers.

I understand that if it's a driver issue, is not a game or engine issue per say, but these graphics cards are really common and affect a great amount of people.

The nVidia GTX 760 one can play the game as long the window size (of 640x360) isn't stretching to a higher resolution (I set up a button to go to 720p or 1080p, stretching the image), or using Alt + Enter to go fullscreen.

Setting

```
subImageFix=true
```

on the **mkxp.conf** file didn't change their issues at all.
Except the Intel HD Graphics, which with time started to see things again. He managed to start the game, where the world shows up flickering, and after a while settles down, and they can even go back to the main menu and see everything fine. But with this setting on, only.

The Intel HD Graphics person, also, does see the "welcome splash image" on the game, then black screen. So something does get rendered at some point. But the issue is alike in all resolutions, as opposed to the nVidia one which can experience the game fully at the smallest resolution.

I am really lost and I feel I've disappointed my users. Any help would be greatly appreciated.

Thank you for your time.

**Comment by PabloNeirotti** [comment]
* Update *

**Intel HD Graphics** can see the game just fine with Steam Overlay off. With or without subImageFix. A shame he can't use Steam, but that's something.

**nVidia GTX 760** isn't affected by turning Steam Overlay off, with or without subImageFix. He can still see the game at the lowest resolution, but not at higher or fullscreen.

So there seems to be different kind of issues going on here...

**Comment by sorlok** [comment]
@PabloNeirotti Not sure if this will work for everyone, but this helped two of my users with their black screen issues:
https://github.com/sorlok/mkxp/commit/422e3c8e6482057af338b88ade4b9c87afb99117

**Comment by Darelbi** [comment]
I'm pretty sure the patch will work, anyway that's an issue of the steam renderer. An "orverlay renderer", should not make assumptions over wich GL state is present, and should restore previous GL state before returning to application space. Do someone already asked Steam to fix that, or "do they assume people is using their proprietary engine wich do not have such issue"?

**Comment by PabloNeirotti** [comment]
Will try it out, guys! Thanks!

I can't get a hold on to Valve. They are unfortunately untraceable even to talk Steam or Steam API. I tried :/.

That's the problem with big companies. You are left your in the dark.

Anyways, thanks guys! I will be giving this a shot!

**Comment by PabloNeirotti** [comment]
I'd like to add that a user, with AMD, no steam overlay, no special 3D settings from the control panel, just can't get the game to work. It's pitch black, regardless screen size and Fullscreen. I don't know if this patch will solve that as well, but let's cross fingers.

**Comment by Ancurio** [comment]
If these issues persist, I suggest trying either mkxp-z or mkxp-freebird.
