### ISSUE TITLE
Detect mkxp

### ISSUE THREAD

**Issue by mattiascibien** [Ancurio/mkxp#133]
Hellio,

I am currently developing a game with VX Ace using mkxp as a test for future Linux and Mac Compatibility. 

As I am using a mouse script that relies on Win32 api this does not work at all under mkxp. Is there any kind of constant declared by mkxp that tells that we are under mkxp so I can do and if to disable mouse support under that?

Thank you.

**Comment by Ancurio** [comment]
That would be `$MKXP`.

That being said, you can try preloading [this script](http://pastebin.com/zXW1hdrx) and see if the mouse script works with it.

**Comment by mattiascibien** [comment]
Ok... Sorry for opening an issue but I did not know any other way to contact you :+1: thank you so much for your fast reply.

**Comment by Ancurio** [comment]
Don't worry, there's absolutely nothing wrong with opening issues to ask questions.
