### ISSUE TITLE
MKXP with Victor Engine - Sfonts

### ISSUE THREAD

**Issue by Zero50** [Ancurio/mkxp#143]
Hello! I am working on a commercial game and I'm having some issues with performance so I decided to try mkxp. And oh my god the game runs great! 
But the fonts look weird...
So I tried to bypass this and use Victor Sant's Sfonts script, which uses an "image" of the font instead of the font file.

https://victorenginescripts.wordpress.com/rpg-maker-vx-ace/sFont/

On the image file of the font, the first pixel is always a colored one which you use between the letters make the engine differentiate the letters.

However when using mkxp, whenever there is space a line is shown with the colour of that first pixel.
Here is an example of what I'm talking about.

http://s15.postimg.org/6mrsjrsgr/sfont_try.png

Is it possible to fix this?
It's still trouble to use sfonts since they mess up some of my scripts but it's better than what I get with normal fonts...

**Comment by Ancurio** [comment]
> Is it possible to fix this?

Without a minimal testcase demonstrating the problem, it's hard to tell.
