### ISSUE TITLE
"Multiple issues"

### ISSUE THREAD

**Issue by PabloNeirotti** [Ancurio/mkxp#147]
Hello there!

I am having a subset of the player base running into troubles running my game.

I don't think it's a scripting thing, as everyone can run it just fine. But some people report the screen hanging randomly, or freezing but being able to move the cursor around and select things - they hear it but can't see it.

I am desperate and lost at the same time. Any help?

This is the thread where they have been reporting these issues:
http://steamcommunity.com/app/375210/discussions/1/364039531224886145/

Thank you anyone in advance for your time.

**Comment by Darelbi** [comment]
Do anyone here thinked to create a 2D tool (similiar to RPGMaker XP) but from scratch without warrying about features like compatiliblity with pre-existing maps? just curious

**Comment by Ancurio** [comment]
As a last effort, you could always have a 2nd launch option that uses the original RMVXA Player.exe instead of mkxp.

**Comment by PabloNeirotti** [comment]
I've been thinking about that. But Steam only launches one app, it doesn't allow the user to pick (even if I found a way to make it work again with the original player: which I could with time).

There is no way to make this work?

**Comment by Ancurio** [comment]
Under Steamworks Settings, you go into Installation -> General, and then add another launch option. Give it some description like "Legacy mode" or similar (that's what Lisa does, for what it's worth).

**Comment by PabloNeirotti** [comment]
I see.

So I tried making several changes, including making an interface to the FFI Library that I switched to since Win32Api wasn't available. I get the game to kinda work, but it's insanely slow, because, it just has 8 months of developing with OpenGL in mind. It's unplayable now, I can't revert to the RPG Maker player :/

No clue as to why on some systems it seems to not paint the screen more than once per Scene? Which is what I collect from these posts.

**Comment by Ancurio** [comment]
Please reopen if this issue persists. I have come across a lot of problems in regards to non-existing / outdated graphics drivers, and Intel in general is garbage on Windows, so if one of your players only has that available, they're kinda out of luck unfortunately.
