### ISSUE TITLE
Missing method Audio.setup_midi()

### ISSUE THREAD

**Issue by dogtopus** [Ancurio/mkxp#149]
Some RGSS3 games (e.g. Mogeko Castle) utilize this method to initialize(?) MIDI. However it is not present in mkxp so the game failed to start.
Add an empty setup_midi() to the Audio module would be enough to resolve this issue since mkxp seems to do MIDI initialization unconditionally (correct me if I am wrong).

PS: I currently add these code to a preload script to workaround this problem:
```ruby
module Audio
    class << self
        def setup_midi
            return
        end
    end
end
```

**Comment by Ancurio** [comment]
0ec1fce4acc0e5cb942ae4fad7d730ee23b30488

Thanks. It had a core implementation seemingly forever, but it looks like I forgot to expose it because almost nobody uses it..
