### ISSUE TITLE
Text gets cutoff in vertical strips

### ISSUE THREAD

**Issue by lunarcloud** [Ancurio/mkxp#153]
![screenshot_20161228_092849](https://cloud.githubusercontent.com/assets/1565970/21524160/068a0654-cce2-11e6-8700-11509399633a.png)

(K)Ubuntu 16.10 Yakkety
Intel HD Graphics 6000
Mesa 13.1.0-devel (Core OpenGL 4.5)
RPG Maker VX Ace game

**Comment by lunarcloud** [comment]
It seems that triggering the same lines produces different results each time in terms of what is obscured. Sometimes nothing is.

**Comment by Ancurio** [comment]
Please try running with `--subImageFix=true` (or the respective mkxp.conf entry).

**Comment by lunarcloud** [comment]
Fixed my issue perfectly. Is there any **reason** that it's disabled by default, then?

**Comment by lunarcloud** [comment]
Just checked the source code. Guess the project simply prefers the fast code to the compatible one for its default.

**Comment by Ancurio** [comment]
The reason it's not on by default is because I try to be optimistic and do not expect the graphics driver to be broken.
