### ISSUE TITLE
Static Events seem to be moving slightly when the player/camera moves

### ISSUE THREAD

**Issue by khkramer** [Ancurio/mkxp#154]
Is there any way to fix this in mkxp?
I'll try uploading a webm of what I'm referring to later today

**Comment by Ancurio** [comment]
mkxp doesn't know anything about events, it only deals in RGSS primitives (Bitmaps, Sprites etc.). You will have to provide a simple test case (ideally a ruby script with a minimal game loop, but a game project is fine too) which exhibits the problem you're seeing in mkxp (and doesn't do it in RMXP).

**Comment by khkramer** [comment]
Sorry for the late response, it turned out to be caused by the scrolling part of Game_Map in my project and not something caused by mkxp itself.
