### ISSUE TITLE
Use encrypted RTP

### ISSUE THREAD

**Issue by radialapps** [Ancurio/mkxp#155]
In creating a custom build, what would be the best practice for mounting an encrypted archive as an RTP without performance losses? I just mean simple encryption, with the key hard coded into the binaries (the reason being to protect the audio files).

**Comment by carstene1ns** [comment]
Not saying this is a good idea to encrypt game data at all, but if I had to do it...
One way to do it for mkxp would be to patch physfs to apply some XOR key to each archive it opens/reads.
This should not need changes to mkxp and you only have to encrypt your archive with the same secret key.

**Comment by Ancurio** [comment]
* encrypted game data
* no performance loss

The above two are mutually exclusive.  
I don't believe PhysFS comes with support for any encrypted formats by default (reading of password protected zips could probably be added, not sure about the complexity of that task). So the only "encryption" available in vanilla mkxp is `rgssad`. I have a small bash utility to create `rgssad` / `rgss3a` archives that I can give you. If you change the XOR keys in both mkxp and the utility, it'd even be "safe" from conventional `rgssad` unpackers.

**Comment by radialapps** [comment]
I'll close this then, since its a bit unrealistic

**Comment by khkramer** [comment]
@Ancurio 

Do you still have this bash script?
I'm packing my rgssad with another tool currently ( with a different key set also in the mkxp source ) but I'm getting Marshal version errors which I'm guessing is due to the utility generating a ruby 1.8 compatible format

**Comment by Ancurio** [comment]
http://ancurio.bplaced.net/mkxp/ttm_pack/ttm_pack.c
