### ISSUE TITLE
Build errors: unsure about library versions

### ISSUE THREAD

**Issue by ntzrmtthihu777** [Ancurio/mkxp#157]
Heyo. Basically, debugging a friend's game to port it to mkxp. Bit of a problem in that the mkxp.exe you've provided does not print a useful name of the errored out script.

Unsure if this is due to an older build of mkxp and this is fixed in tree or what.

**Comment by Ancurio** [comment]
The option to print script names (`useScriptNames=true`) was added in April 14, and the latest win build is from 2015, so it should be available. I can create a new win32 build though if you still need it.

**Comment by ntzrmtthihu777** [comment]
well, it was a stupid error on my part. I found it out at a later date. Question: do you happen to have a sort of 'sdk' with needed libs for mingw? You could do it, sure, but I don't wanna have to make you build it again after each tweak I make to mkxp itself.
