### ISSUE TITLE
Windows builds: Don't embed icon.png.xxd, instead a windows ico.

### ISSUE THREAD

**Issue by ntzrmtthihu777** [Ancurio/mkxp#159]
Will work up a patch for this, but on windows, one typically embeds an icon file via a resource.rc file, processed with windres into resource.o.

Doing so causes the actual file's icon to change to the embedded ico, in addition to the taskbar, alt-tab, and window bar icons.

Could save a small amount of space in the final executable and add a touch of professionalism to the final game.

**Comment by Ancurio** [comment]
Closing this as there's a PR now.
