### ISSUE TITLE
Problem with mirrored sprites.

### ISSUE THREAD

**Issue by khkramer** [Ancurio/mkxp#171]
Whenever the mirror property is set to true, sprites don't appear where they are supposed to, at least not consistent with RMXP behaviour.

I have a feeling this is due to the coordinates being incorrect after a sprite is mirrored, I'll conduct some more tests and update this issue.

**Comment by khkramer** [comment]
Well after some more testing it doesn't seem to happen in one of my older builds of mkxp.
To reproduce the bug just create a sprite and set .mirror to true and the sprite will not be visible.
I've managed to reproduce it on 3 different systems.

**Comment by khkramer** [comment]
Setting the x property of the PosRect to the x property of the rect seems to _rect_ify the problem however the position is off by a few pixels.

**Comment by Ancurio** [comment]
Please try with f172f58c747240599e212f2ede57f37bd393a170

**Comment by khkramer** [comment]
@Ancurio 
Works like a charm :)
