### ISSUE TITLE
Legality

### ISSUE THREAD

**Issue by callmeres** [Ancurio/mkxp#176]
Is mkxp legal to use and can a game be sold?

**Comment by khkramer** [comment]
I can't see any reason why MKXP would not be legal, since Ancurio hasn't reverse engineered any code from the original Game.exe.

Also there are a number of games released on Steam with a mkxp version available.

**Comment by radialapps** [comment]
Yup, if I understand it correctly, mkxp *is* legal. Consider it to be a completely different engine that has syntax eerily similar to RPGXP ;-)

**Comment by callmeres** [comment]
I confirmed with staff member Archeia on rpgmakerweb and was told that mkxp is legal!
