### ISSUE TITLE
Updated macOS app bundle

### ISSUE THREAD

**Issue by vinyldarkscratch** [Ancurio/mkxp#179]
Ali's compiled versions are a little outdated and don't support the newer macOS builds as well, so I thought to compile a new version of MKXP with better support for more recent systems.  🙂

https://drive.google.com/open?id=1x4KB1v9_KXe8T__K4PWHAAKx3dYlZloH (updated Dec. 16, 2017)

Note: compiled pull request #174 (since MKXP fails to compile without it, and the PR is working perfectly now)

**Comment by openmac** [comment]
Thanks @vinyldarkscratch!
I should prepare new builds soon too, but your builds will help those that need them now.
I wonder if you saw my builds on box.com or the mediafire one which uses newer openal for fixing issues with newer versions of macOS.
If you have noticed other issues with newer versions of macOS, please let me know.

**Comment by vinyldarkscratch** [comment]
Heya Ali,

I actually hadn’t seen the MediaFire ones that you were referring to, is it linked somewhere on this repository?  One of the biggest issues I was noticing was that the ones on Box didn’t have proper Retina display support, which caused a few graphical bugs here and there.  I assume SDL updated since your Box builds, so a simple upgrade should to the trick, but I haven’t done my research on the matter, apologies!  😛

- Vinyl Darkscratch-Kazotetsu, Founder of Nightwave Studios
(Sent from my Nightinfection, my iPhone)

--
If you believe you have received this email in error, please contact me at vinyldarkscratch@gmail.com, Twitter @vdscratchy, or Skype at vinyldarkscratch

**Comment by openmac** [comment]
Hi Vinyl,

The link is on the other Mac related issue, but I noticed I have only put one public build in there, I made tons later, but they didn't end up going to the public folder.

Deciding on the SDL version is a tough one, if you go with 2.0.4 and up, you end up adding more issues, like missing window titles and resized windows. Try replacing the MacOS and Frameworks folders of any Freebird Games game or Rakuen with your MacOS and Libraries folder, then open the game. Change to windowed mode, you will see the window is slightly resized, and the window title is missing.
But if you don't go with newer versions of SDL, you will end up having some minor full screen issues with newer versions of macOS.

I have one suggestion though, I have noticed that your build was made against Ruby 2.3 that comes with macOS 10.13, earlier versions of macOS come with older versions of Ruby, so if you don't bundle Ruby in your Libraries folder, your mkxp build will effectively only run on macOS 10.13.

**Comment by vinyldarkscratch** [comment]
Heya Ali,

For the SDL version, it definitely can be a challenge (and luckily they
have a lot of backwards compatibility).  However, on SDL 2.0.6, I haven't
actually experienced those problems with the window title and resizing, at
least not with MKXP?  (I haven't played around with other programs that use
SDL.  :P)

As for Ruby, oh shoot, did I not include it in the bundle?  I knew there
was something I forgot about...  Thanks for letting me know!  (I will admit
I'm still learning about deployment of applications, heh...)  Fixing that
right now!

- Vinyl Darkscratch-Kazotetsu, Founder of Nightwave Studios
https://www.nightwave.co
Free Translation Services: https://www.speaklouder.co

vinyldarkscratch@gmail.com / dark.tailed.wolf@gmail.com
Skype: vinyldarkscratch
Phone: (707) SHADOW-8 (Text-only)
http://www.queengoob.org

http://soundcloud.com/vdscratchy
http://vinyldarkscratch.bandcamp.com

http://youtube.com/VinylDarkscratch
http://vinyldarkscratch.deviantart.com/ <http://waseci.deviantart.com/>

https://github.com/vinyldarkscratch
http://vinyldarkscratch.tumblr.com
https://plus.google.com/+KuraiAtonitsuka
http://www.twitter.com/vdscratchy

**Comment by vinyldarkscratch** [comment]
New bundle's link: https://drive.google.com/open?id=1x4KB1v9_KXe8T__K4PWHAAKx3dYlZloH

**Comment by Ancurio** [comment]
Thanks for your contribution, closing this right now to declutter. Hopefully we can get automated builds going in the future.
