### ISSUE TITLE
Loading Ruby Gems

### ISSUE THREAD

**Issue by GeigerCounter** [Ancurio/mkxp#181]
I tried using `require: 'os'` to include the os gem installed on my Linux comp. I need the OS library for some error checking purposes and to decide which scripts to load when. Mkxp threw an error "cannot load such file -- os". How can I load Ruby gems installed to my system? Or, barring that, how do I load Ruby gems from the game directory?

**Comment by ReinUsesLisp** [comment]
Maybe 'os' gem is compiled in your home directory. Try running: `$ sudo gem install os` so it's installed in `/usr` instead of `/home/<user>/.local`.
You can also try using `rubyLoadpath` in mkxp.conf or command line:
e.g.: `$ ./mkxp --rubyLoadpath /usr/lib/ruby/`

**Comment by Ancurio** [comment]
Good tips from ReinUsesLisp, please reopen if you need further help.
