### ISSUE TITLE
Blurry after changing defScreenW/defScreenH

### ISSUE THREAD

**Issue by M3rein** [Ancurio/mkxp#183]
Apologies if this is a basic question which may even be anwered somewhere.

I'm using RGSS 3 and want a 512x384 screensize. I set `defScreenW` and `defScreenH` to these values, but things get blurry. I messed with a couple values like `fixedAspectRatio` and `smoothScaling`, but to no avail.

Is there something I'm missing, or is this a bug?

Note: I'm using the prebuilt Windows binary. I'd like to compile the thing (because I think the binary is outdated), but I have no clue how to do so.

PS: It's fast as hell and looks super promising. If I can get this out of the way, I'd be forever grateful. Awesome job on this project.

**Comment by Ancurio** [comment]
Yeah sorry those config entry names are confusing as hell and I should probably change them in the future. What they do is just set the window size at startup; the resolution at which the game is rendered is controlled by RGSS (`Graphics.resize_screen`)

**Comment by M3rein** [comment]
I found that out shortly after, yeah :)
Should’ve mentioned it, sorry about that.

I’ve used it for a bit now and I’m absolutely in love (as are others in the community I’m in). Thanks a lot for all your hard work!
