### ISSUE TITLE
Setting "customScript" in mkxp.conf sets the game's title to that

### ISSUE THREAD

**Issue by M3rein** [Ancurio/mkxp#184]
I have an external script load a bunch of .rb files, but when I tell it to load that by setting "customScript" to the path in `mkxp.conf`, it sets the title of the game to that file.

Here's what I mean:
![](https://i.imgur.com/RNZUxkH.png)

If I comment that line out, it shows up fine, but then it wouldn't load my .rb files.

**Comment by carstene1ns** [comment]
Not sure what you are trying to do here, can you tell us what the scripts are supposed to do? Only thing that comes to mind without answering this question is that you may have confused `customScript` and `preloadScript`?

Quoting the sample configuration file:
```ini
# Instead of playing an RPG Maker game, execute a single plain text script instead
customScript=/path/to/script.rb

# Define raw scripts to be executed before the actual Scripts.rxdata execution starts
preloadScript=my_win32_wrapper.rb
preloadScript=ruby18_fixes.rb
```

Of course it would set the game title to the custom script, because there is no actual game attached... 😀

**Comment by M3rein** [comment]
Oh, well, my `customScript` loads and executes my `rb` files at the moment.

I ideally want it to use just rb files. The actual game title is a part of `Game.ini`, which in that case it wouldn't use. Is there a way to go around that, so not to use Game.ini but still have the title be whatever I want?

**Comment by carstene1ns** [comment]
Depending on wether you want to use a custom build of mkxp, you could patch this for example: https://github.com/Ancurio/mkxp/blob/master/src/config.cpp#L288 or maybe add a new config option `customTitle` for general use.

**Comment by M3rein** [comment]
I do want to, but I have no idea how to compile it myself 😕

**Comment by Ancurio** [comment]
Having a config entry to override the game title seems non-invasive enough; I'll try to get it done today evening.

**Comment by M3rein** [comment]
Sweet, that'd be useful.

When you've implemented it, could you perhaps also update the Windows binary? I'm not sure how I'd compile it myself so it'd help if you did it for me <3

**Comment by Ancurio** [comment]
s/evening/this weekend/g

**Comment by Ancurio** [comment]
7d9a85dbbd43f7dd26ef5ce07b2772bbd1e59a3a is in master. I will compile a new windows bin tomorrow (need sleep >.>)

**Comment by Ancurio** [comment]
No guarantees that this works: http://ancurio.bplaced.net/mkxp/mingw32/mkxp-20171211.zip

**Comment by M3rein** [comment]
It works, but it resets itself to `entry.rb` once it's actually loaded everything.
![](https://i.imgur.com/qr2HM4J.gif)

**Comment by Ancurio** [comment]
http://ancurio.bplaced.net/mkxp/mingw32/mkxp-20171212.zip

Should be fixed with FPS display now. I have no clue why the FPS are on by default though, it doesn't happen on my Linux box.

**Comment by M3rein** [comment]
The title is fixed now, thank you. And uh... I guess I had `printFPS=true` in my config for some reason =( Sorry.

Thanks a lot for the support 👌
