### ISSUE TITLE
Error reading Game.ini due to case sensitive parsing.

### ISSUE THREAD

**Issue by emmauss** [Ancurio/mkxp#187]
MKXP cant read game.ini files which have variables in lower cases. This is different from how rpgmaker reads the ini files. RPGmaker is case insensitive when reading inis, while mkxp is sensitive. This gives an error saying that games scripts not found when using mkxp, while the game.exe runs normally.

**Comment by hanetzer** [comment]
https://github.com/Ancurio/mkxp/blob/master/mkxp.conf.sample#L216 @emmauss should be helpful,
maybe?

**Comment by emmauss** [comment]
@hanetzer it is supposed to be enabled by default, there should be no need to force it.

**Comment by hanetzer** [comment]
@elizagamedev ah, fair enough. This may be an actual error, then,
at least as far as a 1:1 rgss compat goes.

**Comment by Ancurio** [comment]
If someone knows how to tell `boost::program_options` to do the ini parsing in a case-insensitive manner, this can be implemented

**Comment by hanetzer** [comment]
https://stackoverflow.com/questions/15419665/boost-program-option-case-insensitive-parsing
may be of use, I don' know the guts of boost::p_o to know that this is right or not.

**Comment by Ancurio** [comment]
Thanks for googling, but that seems to be only applicable to command line parameters (I already tried). Also searched the tutorial but to no avail. I kinda don't wanna have to hand-write a config parser just for this..

**Comment by carstene1ns** [comment]
TBH I have also thought about dropping boost completely. Question is, if mkxp wants to target C++11 or still stay compatible with older standards.

**Comment by hanetzer** [comment]
@carstene1ns honestly I'd be very happy if boost drops out of it, because its the only dep
it has with dicks for build system. It would be very doable to set up a good CI server setup
to deploy builds for windows and osx much more easily.

**Comment by Ancurio** [comment]
@carstene1ns Dropping the boost `hash` and `set` classes works, but what do you want to do about `program_options`? Handroll your own?

**Comment by lacc97** [comment]
@Ancurio I wrote an ini parser that does not use Boost. It is PR https://github.com/Ancurio/mkxp/pull/207.

**Comment by Ancurio** [comment]
Should be fixed now via #207.
