### ISSUE TITLE
SDL_sound development package not found when building on Linux

### ISSUE THREAD

**Issue by sukoshijon** [Ancurio/mkxp#188]
Hi,
I'm trying to build mkxp on Linux, since the latest prebuilt binary for Linux is the 2015 one. Unfortunately, even after installing the SDL_sound port, I've been unable to get it to build due to both qmake and cmake being unable to find it.

**Comment by hanetzer** [comment]
You have to use the patched SDL_sound package which is modified to work
with SDL2. [Ancurio/SDL_sound](https://github.com/Ancurio/SDL_sound)

**Comment by sukoshijon** [comment]
I have that. I stated that in the original post, but it probably wasn't clear enough.

**Comment by hanetzer** [comment]
Well, could you provide a log of qmake/cmake trying to find it? There is probably a switch to turn on verbose error reporting for either. In any case, afk for a bit, nap.

**Comment by sukoshijon** [comment]
[Here's the console output ](https://pastebin.com/raw/HDmbDLT4). And [CMakeOutput.log](https://pastebin.com/raw/s9Dm81GQ) as well.

**Comment by Ancurio** [comment]
https://askubuntu.com/a/210235

**Comment by sukoshijon** [comment]
Okay, so now that I've done that, and ran cmake/qmake, what do I do? I'm not really experienced with building things so I don't really know what's supposed to happen.

**Comment by Ancurio** [comment]
Would it be easier if I just updated the prebuilt binaries for Linux? Building mkxp is really only recommended for people experienced with compiling software from scratch.

**Comment by sukoshijon** [comment]
There's a couple of things I wanted to modify in the source code though. It would be easier if I knew how to compile it so that I didn't need to get someone else to do it every time I made a change.

**Comment by hanetzer** [comment]
@sukoshijon not sure about qmake, but after cmake you would run make (unless you specified
a different cmake generator [I like ninja; builds very fast, much faster than gnu make usually])

**Comment by sukoshijon** [comment]
Yeah, I ran make and it threw `[  1%] Generating XXD for assets/icon.png
make[2]: XXD_EXE-NOTFOUND: Command not found
make[2]: *** [CMakeFiles/mkxp.dir/build.make:162: icon.png.xxd] Error 127
make[1]: *** [CMakeFiles/Makefile2:67: CMakeFiles/mkxp.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
` at me.

**Comment by hanetzer** [comment]
@sukoshijon ah, you need vim installed (unless whatever distro you are using packages xxd separately).
Query you distro support channels or package manager to find out. Basically xxd turns a binary asset
into a c-style header file which can be #include'd into a program.

**Comment by sukoshijon** [comment]
Okay, now it can't find SDL_sound when I run make

**Comment by Ancurio** [comment]
I updated the prebuilt Linux binaries

**Comment by sukoshijon** [comment]
While that helps _some_ of the issue, I can't change the prebuilt binaries. On the subject of make not being able to find SDL_sound, I think I installed SDL_sound wrong (I put SDL_sound.pc into the pkgconfig folder), because changing the path didn't work.

**Comment by Ancurio** [comment]
You might also try the dependency kit mentioned in the Readme (you might have to add `-D_GLIBCXX_USE_CXX11_ABI=0` to the defines if you're using a newer version of gcc)

**Comment by sukoshijon** [comment]
That worked! Thank you for the help, it is much appreciated.
