### ISSUE TITLE
[RGSS Accuracy]: if argv[1] contains 'debug', 'test', or 'btest' set variables in ruby.

### ISSUE THREAD

**Issue by hanetzer** [Ancurio/mkxp#190]
In RPGXP, playtesting a game via the 'Playtest' green arrow button runs `Game.exe debug`,
which sets `$DEBUG = true` within the ruby context. Using the battle test runs a similar cmd,
`Game.exe btest`, which sets `$BTEST = true` which hijacks Scene_Title to run the battle
test.

It would probably be best to define guard this with `NDEBUG` so as not to work in release
builds of games.

Apparently XV/Ace does `Game.exe test` and sets `$TEST = true`.

This should be a simple change in src/main.cpp#L220 or so; I would do it myself but I'm
not sure how manipulating argc/argv would trickle-down alter further behavior down the
pipeline.

**Comment by Ancurio** [comment]
I'm confused; when would you ever launch mkxp.exe passing those parameters manually? Or is that what you want, to have mkxp recognize them and act accordingly?

**Comment by hanetzer** [comment]
You would not do it manually, but if you're using mkxp along with an existing maker
(likely the windows port of mkxp, but I'm also considering using mkxp as a replacement
Game.exe for my PlayOnLinux RPG Maker XP script in order to ease requirements)
in order to gauge script changes with the enhancements to mkxp.
