### ISSUE TITLE
Generall support for the steamapi (all plattforms)

### ISSUE THREAD

**Issue by TomTheDragon** [Ancurio/mkxp#201]
I know a few people that made games they distribute over the steam platform and they are now looking to get their games also running under other OSs like linux and mac.
The problem is that they intrgrated the steamapi mostly for the Steam archiment support.
Mkxp would be an awesome and much more faster running replacement for the old, aging RPG maker engine.
But unfortunately it does not seem to be compatible with the engine yet.

**Comment by Ancurio** [comment]
> But unfortunately it does not seem to be compatible with the engine yet.

You can use [steamshim](https://hg.icculus.org/icculus/steamshim/) to use the SteamAPI without violating GPL conditions, as was done in other ports. Also see [mkxp-abs](https://github.com/Ancurio/mkxp-abs), [mkxp-oneshot](https://github.com/elizagamedev/mkxp-oneshot).
