### ISSUE TITLE
Attribution for certain sourcefiles?

### ISSUE THREAD

**Issue by hanetzer** [Ancurio/mkxp#203]
For example, debugwriter.h. I rather like the way it works and whatnot, and would
like to use it in a project of my own. I would think a header like this would be enough?
```c
/*
** debugwriter.h
** This file is part of <myproject>
** Taken from mkxp
**
** Copyright (C) 2013 Jonas Kulla ...
** Copyright (C) 2018 Marty Plummer .... (if I make changes to it)
**
** gpl text
*/
```
Would this be sufficient?

**Comment by Ancurio** [comment]
Sure, go ahead.
