### ISSUE TITLE
version with win32api

### ISSUE THREAD

**Issue by klebersonromero90** [Ancurio/mkxp#204]
I know the project is meant to be multiplatform but does it not compile a version like win32api? is a super required feature that we use on windows primarily to make systems online.

it would be possible?

**Comment by dogtopus** [comment]
It's always possible to use the Win32API stub made by @Ancurio to emulate certain APIs. In your case you could include the standard Ruby library and write a binding between the Ruby socket API and Win32API stub. Or you could go more intrusive by writing two different implementations for mkxp and stock RGSS engine. Automatically switching implementations is possible by detecting the presence of `MKXP` module.

**Comment by Ancurio** [comment]
@klebersonromero90 Even if I tried, Win32API is deprecated since Ruby 1.9 (and mkxp builds with much newer versions).
Doesn't ruby have some Socket classes built in? Not sure why you would need win32api for online stuff.

**Comment by klebersonromero90** [comment]
I did not get to test but create an input keyboard without win32api is a bit tense

**Comment by klebersonromero90** [comment]
How to use sockets ?

**Comment by Ancurio** [comment]
@klebersonromero90 My bad, turns out the Socket is part of the standard library and not core Ruby, so it's not compiled into mkxp. Can't think of a solution at the moment that wouldn't require a custom build.

**Comment by frozenLake** [comment]
Shouldn't this be implemented anyway, so as to complete the mission statement of being able to run games created with the RPG Maker software natively without changing a single file?

**Comment by dogtopus** [comment]
@frozenLake Implementing Win32API is not practical because:

1. It is basically equivalent to reinventing wine
2. If the game only requires a few of the APIs to run (most common cases), then it is more practical to just implement these APIs using plugins. While plugins are not explicitly supported in mkxp, it supports script preloading and setting ruby library path, which is almost equivalent to a plugin system if used correctly.

So tl;dr why bother?

**Comment by Ancurio** [comment]
[mkxp-z](https://gitlab.com/zzoro/mkxp-z) seems to have gotten a lot further than my own project in accommodating Win32API.
