### ISSUE TITLE
Is it possible to call `snap_to_bitmap` in RMXP?

### ISSUE THREAD

**Issue by khiav223577** [Ancurio/mkxp#205]
This feature seems to have beed implemented but blocked by the version check.

https://github.com/Ancurio/mkxp/blob/55f1542c767eae072f354466f27d1c5de8700a3a/binding-mri/graphics-binding.cpp#L202-L213

I tried to set `rgssVersion` to 2 (or 3) in `mkxp.conf` in order to bypass the check. It did work, but also broke many other things since my game is written in RGSS1.

Is there a way to access this method while maintaining `rgssVersion` in 1?

**Comment by carstene1ns** [comment]
Does this work in the original engine? The check could be (re-)moved then.

**Comment by khiav223577** [comment]
Original RMXP engine doesn't have `Graphics.snap_to_bitmap` method. Not sure if removing the check is a good idea or not. Or could we reference them via custom module? For example, `MKXP::Graphics.snap_to_bitmap`

**Comment by Ancurio** [comment]
Not possible with a stock mkxp build (maybe one might hack the binary to skip the conditional jump, but that's about it).

What you're asking for is a modified mkxp that doesn't behave like the original engine. This almost always requires a custom build.
