### ISSUE TITLE
Cannot generate a safe linker search path for target mkxp

### ISSUE THREAD

**Issue by edwinacunav** [Ancurio/mkxp#208]
Whenever I follow your instructions found in your Dependency Kit README file this is what happens.

cmake -DBOOST_INCLUDEDIR=$BOOST_I -DBOOST_LIBRARYDIR=$BOOST_L ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'sigc++-2.0'
--   Found sigc++-2.0, version 2.4.0
-- Checking for module 'pixman-1'
--   Found pixman-1, version 0.32.6
-- Checking for module 'physfs>=2.1'
--   Found physfs, version 2.1.0
-- Checking for module 'vorbisfile'
--   Found vorbisfile, version 1.3.4
-- Checking for module 'sdl2'
--   Found sdl2, version 2.0.4
-- Checking for module 'SDL2_ttf'
--   Found SDL2_ttf, version 2.0.12
-- Checking for module 'SDL2_image'
--   Found SDL2_image, version 2.0.0
-- Checking for module 'SDL_sound'
--   Found SDL_sound, version 1.0.1
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   program_options
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Checking for module 'ruby-2.1'
--   Found ruby-2.1, version 2.1.0
-- Configuring done
CMake Warning at CMakeLists.txt:400 (add_executable):
  Cannot generate a safe linker search path for target mkxp because files in
  some directories may conflict with libraries in implicit directories:

    link library [libopenal.so] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/user/MK/mkxp-depkit/lib

  Some of these libraries may not be found correctly.

-- Generating done
-- Build files have been written to: /home/user/MK/build

Yeah, I found build files but no executable right there... Am I missing anything here? I thought the dependency files already included a custom version of OpenAL and ZLIB, I don't know why it doesn't find them.

**Comment by carstene1ns** [comment]
Did you execute `make` afterwards?

**Comment by edwinacunav** [comment]
You're missing two points here, it doesn't find files that were provided to ensure compatibility and that it doesn't pick any of them to set the path.

**Comment by edwinacunav** [comment]
Well, it's gotten worse here... Can anybody check the attached file and tell me how to fix both issues?
[make results.txt](https://github.com/Ancurio/mkxp/files/2427611/make.results.txt)

**Comment by carstene1ns** [comment]
For the second (build) error: You need to update the `physfs` library to at least 3.0. I guess the dependency kit is just outdated (another approach, *untested*: revert my patch [#174](https://github.com/Ancurio/mkxp/pull/174.patch) and use the older version)

The cmake warning is not really an issue when you do not want to distribute your executables, as it simply means it will link in system libraries instead of the ones from the dependency kit (which may work fine).

**Comment by edwinacunav** [comment]
Hmm I will try both the patch and the newer version of physfs.

The problem is that I don't wanna use the system libraries for a couple of people here want to use the same build I'd be using on my PC.

**Comment by edwinacunav** [comment]
It seems there is ever more to cover than first thought, I've got another couple of errors while compiling it.

[make new results.txt](https://github.com/Ancurio/mkxp/files/2429658/make.new.results.txt)

**Comment by edwinacunav** [comment]
So do you got any idea why is that happening? Got any ideas on how to solve it, guys?

**Comment by carstene1ns** [comment]
IMO the dependency kit needs to be updated.

**Comment by Ancurio** [comment]
I have updated the depkit with the new phsysfs and new instructions for using the old C++ abi (I think the included version of Boost is what requires this), please try again.

**Comment by edwinacunav** [comment]
Just a suggestion... Wouldn't it be better if all dependencies had been updated before people try to compile it? Or does it include more updates than the ones you've mentioned so far? I'd like to know what else was updated there.

**Comment by Ancurio** [comment]
> Just a suggestion... Wouldn't it be better if all dependencies had been updated before people try to compile it? Or does it include more updates than the ones you've mentioned so far? I'd like to know what else was updated there.

I can't remember what else I updated, but in general my policy: If it works, don't update needlessly.
