### ISSUE TITLE
Crosscompiling mkxp then switch to windows to run it but opens a console

### ISSUE THREAD

**Issue by edwinacunav** [Ancurio/mkxp#215]
I'm unsure whether this is an issue or not, but when I used mingw to compile a 64 bit binary executable I noticed it always opens the console window aka command window to let me know it loaded stuff like fluidsynth or not. How can I also compile a version that does not open that secondary window? I'm not saying it's bad to get a console window (as support) but ready to distribute games won't look as good as expected if the executable keeps opening that second window...
I'm working on *Ubuntu using mingw64 to crosscompile to Windows (especifically 8.1). By the way, I also tried to compile it on Windows via mingw but it was a total mess... :S so I would prefer not to go through that ever again if possible. XD

**Comment by carstene1ns** [comment]
Do you use CMake? Add `WIN32` property to the [CMakeLists.txt](https://github.com/Ancurio/mkxp/blob/master/CMakeLists.txt#L400).

I suggest we should add some logic like [we do for EasyRPG Player](https://github.com/EasyRPG/Player/blob/master/CMakeLists.txt#L386-L392) here, too.

**Comment by Ancurio** [comment]
> • How do I remove DOS command windows?
> In the link step add a "-mwindows" switch to the command line.

http://www.mingw.org/wiki/FAQ

**Comment by edwinacunav** [comment]
Thank you, guys, but I had figured it out during my absence. I'm sorry for not showing up earlier to close the issue, he, he. What's positive about this is that many more people should now get access to the same info as I did. Thank you again for your assistance.
