### ISSUE TITLE
Attempting to run a particular game with no success. (FNAFB)

### ISSUE THREAD

**Issue by TheExtremeGamer** [Ancurio/mkxp#216]
Greetings, I am attempting to run a specific game.

I am using the precompiled binaries from Github on Ubuntu 18.04.2 LTS.

Here is the game I am trying to run (I would directly say the title but I am not sure there isn't some sort of elusive "no cussing policy". : https://gamejolt.com/games/five-nights-at-f-boy-s-final-mix/53422

I haven't the first clue what is wrong here, however.

When opening via mkxp I get this a blank game screen with this popup message.

" Script '{0139}:73' line in '<module: NameError occured.
uninitialized constant EFE::Win32API"

(And a screenshot in case I failed at typing that)

![workspace 1_026](https://user-images.githubusercontent.com/42900573/53136097-947a4e80-3575-11e9-9c56-670b253584ff.png)

I then attempt to run "mkxp.amd64" (with the Game Files obviously) via the terminal and I get this.

________________

[Typing in "./mkxp.amd64"]
RGSS version 3 (VX Ace) 
ALC_SOFT_pause_device present 
GL Vendor    : Intel Open Source Technology Center 
GL Renderer  : Mesa DRI Intel(R) Ivybridge Mobile  
GL Version   : 3.0 Mesa 18.0.5 
GLSL Version : 1.30 
{0139}:73:in `<module:EFE>': uninitialized constant EFE::Win32API (NameError)
	from {0139}:57:in `<main>'
[Pressing Ok on the Error]
 
EventThread termination requested 
RGSS thread ack'd request after 0 ms 
Shutting down. 
_________________

I've read a few things with regard to no Win32 Support but I figured I should still send a report.

**Comment by carstene1ns** [comment]
Depending on what parts of the Win32API this game depends, it will not work.
If it is just the basic stuff mentioned in the README, it might be patched.
However, not going to look into this. Suggestion: Extract the game content and have a look at the win32 stuff.

**Comment by Ancurio** [comment]
Many games unfortunately use Windows-specific functionality to get around the heavy limitations of the base engine; porting those games to run on mkxp can range from a few line changers, a couple weeks of work, up towards almost impossible. It's hard to tell which one this is, if you direct me to where I can find the game files or (even better) send me the `Game.rgss3a`, I can take a quick peek without promises.
