### ISSUE TITLE
Error "The RGSS script seems to be stuck and mkxp will now quit."

### ISSUE THREAD

**Issue by corboblan** [Ancurio/mkxp#229]
Hi I haven't had a problem like this until recently. Every time I went into a battle the game would freeze then the error "The RGSS script seems to be stuck and mkxp will now quit." would popup. I narrowed it down by removing the battle theme, then it worked. But then I used a .mp3 and a .ogg file and it continued to work. However when I tried using a different .wav file it crashed with that error. Can someone help me figure this out? Thank you.

**Comment by cremno** [comment]
Is it possible to share the offending file(s)? If it isn't could you at least post more info about it (try your favorite audio player or MediaInfo) and the mkxp build you're using?

The audio in WAV files can be encoded in many different ways including MP3. It's also one reason mkxp officially relies on a SDL_sound fork: IMA ADPCM support.

**Comment by corboblan** [comment]
It's every single .wav file I use. I had this problem all of the sudden. I just encode them to mp3 instead.

**Comment by cremno** [comment]
If not even the RTP WAV files can be played then something is really wrong especially when it used to work. Have you recently replaced your mkxp executable with another one? Where did the executable come from? Did you compile mkxp by yourself? Which compiler/operating system?

Btw. Ogg Vorbis is a preferable format unless you're also targeting the original RGSS1 (RGSS104E.dll on Windows, mkxp on Linux/mac os). It has to read the complete file before it can be played whereas MP3 files can be streamed.

**Comment by corboblan** [comment]
I didn't compile it myself. Could you explain to me how to compile it correctly? Sorry for the very late response. I'm using Windows 10. I'm somewhat of a noob with this whole thing

**Comment by cremno** [comment]
Where did your mkxp.exe come from? I've tried the latest [pre-built one](http://ancurio.bplaced.net/mkxp/mingw32/mkxp-20190518.zip) with a few WAV music files and they were all playing fine (zero graphical stuff though).

**Comment by Ancurio** [comment]
Please provide a minimal ruby script + wav file that reproduces the problem you're having, and reopen this issue. Thanks.
