### ISSUE TITLE
Error 'Script 'fuyllscreen' line 14: NameError occureduninitialized constant Module::Win32API'

### ISSUE THREAD

**Issue by ManUsia5** [Ancurio/mkxp#236]
sorry I don't really know **English**, so I'll get to the point.
when i will start the game i get this error message :

`Script 'fuyllscreen' line 14: NameError occureduninitialized constant Module::Win32API`

How to fix it ? hElp me

**Comment by ManUsia5** [comment]
i am on ubuntu 16._04_

**Comment by tcrane20** [comment]
https://github.com/Ancurio/mkxp#what-doesnt-work-yet
