### ISSUE TITLE
Best Way to Detect if Running mkxp?

### ISSUE THREAD

**Issue by KainNobel** [Ancurio/mkxp#244]
How do you check if running RMXP's oldschool Game.exe or the mkxp program? I need to enable/disable Win32API related functions but I don't know how to detect which is being used.

**Comment by cremno** [comment]
There are a lot of possible checks but I'd simply write:
```ruby
defined? MKXP
```

[`MKXP` is a module defined by mkxp.](https://github.com/Ancurio/mkxp/blob/380b676777b101a7d6648a8e6b9a226a8984bbc0/binding-mri/binding-mri.cpp#L144-L148)
