### ISSUE TITLE
Window content won't draw outside of a 640x480 region

### ISSUE THREAD

**Issue by Speak2Erase** [Ancurio/mkxp#248]
![image](https://user-images.githubusercontent.com/54482069/150669439-739e1e89-58a0-4b48-9a28-2adba5cb8753.png)

**This is using potentially unintended behavior.**
[Graphics.cpp line 929 and 930](https://github.com/Ancurio/mkxp/blob/master/src/graphics.cpp#L929) have been changed so the window can be resized to any resolution.
Here's a small test case I came up with:
```rb
Graphics.resize_screen(960, 540)
window = Window.new
window.x, window.y, window.width, window.height = 0, 0, 960, 540
skin = Bitmap.new(192, 128)
skin.fill_rect(Rect.new(0, 0, 192, 128), Color.new(255, 0, 0))
window.windowskin = skin
window.contents = Bitmap.new(window.width, window.height)
window.contents.fill_rect(Rect.new(0, 0, 960, 540), Color.new(0, 255, 0))

loop do
  Graphics.update
  Input.update
  window.update
end
```
This should look like this:
![image](https://user-images.githubusercontent.com/54482069/150669734-cbe1d92b-6922-402d-988b-198ec7cc024d.png)

If by some miracle it does not, well, I'm an idiot and I screwed something up in one of my [mkxp forks.](https://github.com/Luminol-Editor/Luminol-ModShot)

**Comment by GamingLiamStudios** [comment]
I believe [this](https://github.com/Ancurio/mkxp/blob/380b676777b101a7d6648a8e6b9a226a8984bbc0/src/graphics.cpp#L50) would be the cause. It is used in [GraphicsPrivate](https://github.com/Ancurio/mkxp/blob/380b676777b101a7d6648a8e6b9a226a8984bbc0/src/graphics.cpp#L484) to allocate the usable graphics area.
