### ISSUE TITLE
 Sudden crash : Script 'Zeus Map Effects' - line 85: No MethodError occured.

### ISSUE THREAD

**Issue by bakustarver** [Ancurio/mkxp#253]
OS: Ubuntu 22.04
Checked also in JoiPlay, works great

log:
-------------------------------------------------------------
RGSS version 3 (RPG Maker VX Ace)
ALC_SOFT_pause_device present
Backend      : OpenGL
GL Vendor    : AMD
GL Renderer  : AMD Radeon Vega 3 Graphics (raven2, LLVM 15.0.7, DRM 3.42, 5.15.0-56-generic)
GL Version   : 4.6 (Compatibility Profile) Mesa 23.1.5 - kisak-mesa PPA
GLSL Version : 4.60
libpng warning: iCCP: known incorrect sRGB profile
1
1
1
1
1
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
0.7
libpng warning: iCCP: known incorrect sRGB profile
0.3
0.3
0.3
0.3
0.3
138:Zeus Map Effects:85:in `update_animation_value': undefined method `update_animation_Integer' for #<Game_Map_Effects:0x00007f5947d41730 @active=true, @refresh_rate=30.0, @back=false, @ox=320, @x=320, @oy=240, @y=240, @zoom_x=4.0, @zoom_y=4.0, @zoom2=20.0, @angle=0.0, @wave_amp=1.0, @wave_length=180, @wave_speed=360, @wave_phase=5752.0, @mirror=false, @opacity=255, @blend_type=0, @color=(0.000000, 0.000000, 0.000000, 0.000000), @tone=(0.000000, 0.000000, 0.000000, 0.000000), @hue=0, @pixelize=1.0, @pixelize2=10.0, @blur_division=4.0, @blur_fade=1.0, @blur_animation=0.0, @gaussian_blur_length=0.0, @linear_blur_angle=0.0, @linear_blur_length=0.0, @radial_blur_angle=0.0, @zoom_blur_length=0.5, @motion_blur_rate=0.0, @za_animations={:@wave_length=>[180, 180, 1, 1, nil], :@wave_speed=>[360, 1080, 0, 1, nil]}> (NoMethodError)
        from 138:Zeus Map Effects:74:in `block in update_animations'
        from 138:Zeus M
![1](https://github.com/mkxp-z/mkxp-z/assets/66978329/68dffbe8-98ee-4cd5-98d6-7e917c07a369)
ap Effects:72:in `delete_if'
        from 138:Zeus Map Effects:72:in `update_animations'
        from 138:Zeus Map Effects:470:in `update'
        from 145:Tile Swap:786:in `update'
        from 105:Scene_Map:62:in `update'
        from 156:Simple HUD:143:in `update'
        from 160:Galv's Variable Instance Bars:174:in `update'
        from 103:Scene_Base:14:in `main'
        from 156:Simple HUD:139:in `main'
        from 142:Basic Options Menu:641:in `run'
        from 143:Scene Interpreter:117:in `run'
        from 166:Main:7:in `block in <main>'
        from 166:Main:7:in `rgss_main'
        from 166:Main:7:in `<main>'
RGSS thread ack'd request after 10 ms
Shutting down.
![1](https://github.com/mkxp-z/mkxp-z/assets/66978329/99935e30-8ea8-4f10-9c70-8255a56bbb2e)

**Comment by Ancurio** [comment]
First: you're running [mkxp-z](https://github.com/mkxp-z/mkxp-z), not plain mkxp

Second: you've encountered what appears to be a script issue. in case behavior between mkxp-z and Player.exe differs, please try isolating the issue further
