### ISSUE TITLE
Providing full keyboard input (Win32API emulation)

### ISSUE THREAD

**Issue by Ancurio** [Ancurio/mkxp#73]
The following user32.dll functions are commonly used in scripts to query keyboard keys:

[GetKeyState](http://msdn.microsoft.com/en-us/library/windows/desktop/ms646301%28v=vs.85%29.aspx): Queries the current state of a key, and also whether keys such as caps lock are toggled on

[GetAsyncKeyState](http://msdn.microsoft.com/en-us/library/windows/desktop/ms646293%28v=vs.85%29.aspx) Queries the current state, but also reports whether the key was pressed inbetween calls (so key presses are never missed due to timing)

[GetKeyboardState](http://msdn.microsoft.com/en-us/library/windows/desktop/ms646299%28v=vs.85%29.aspx): Like `GetKeyState`, but copies the state of all virtual key codes into a 256 byte array

The first two functions take [Virtual Key Codes](http://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx) as parameters, which from what I understand, act similarly to SDL scancodes (ie. raw identifiers of physical keys, unaffected by keyboard layouts). The first few codes represent the mouse buttons, which are already available via mkxp's Input module extensions.

The way to enable implementing these that I currently have in mind is this: A single new function (let's call it `raw_key_states`, either under the `System` or `Input` module) returns a 512 byte string into which all SDL scancode states are memcpied into. We already keep such a state array anyway, so the new code literally amounts to a few lines.

For `GetKeyState`, we just translate the windows key code to the corresponding SDL one and return the byte in the array. I'm not sure if it's worth to do extra work for the special `GetAsyncKeyState` behavior of not missing events; in practice, the RGSS Input functions act like `GetKeyState` too. As for the state of toggled keys (capslock, numlock etc.), I don't think anyone makes use of this so it's not worth considering either. One thing I'm not sure of yet is how often to retrieve the raw SDL keystate array. In my current code I hook into Graphics.update and refresh one shared array there once per frame. I assume that a game that doesn't call `Graphics.update` very often or not at all cannot do anything useful anyway, so that shouldn't lead to complications where script code expects completely fresh key states.

For `GetKeyboardState` one would just iterate through all available Windows Key Codes and write the result of `GetKeyState` into the provided string buffer.

Here's the tentative [patch](http://pastebin.com/5dxUUKjm) for mkxp to implement `raw_key_states`, and here's my current [win32api wrapper script](http://pastebin.com/zXW1hdrx) that makes use of it.

If you have any comments / ideas / suggestions, please post them!

**Comment by JeremyRand** [comment]
> here's my current [win32api wrapper script](http://pastebin.com/zXW1hdrx) that makes use of it.

Any reason this wrapper isn't part of the Git repo?

**Comment by Ancurio** [comment]
@JeremyRand the reason is that I didn't consider it good quality code, just barely enough to make certain projects work. As for license, feel free to use it under CC0.
