### ISSUE TITLE
Zlib module should be included as standard

### ISSUE THREAD

**Issue by Daverball** [Ancurio/mkxp#82]
RPGMaker has a built-in Zlib module, which is also part of the extensions ruby provides. Now you could just add the extension manually, but MKXP is already linking against libz so I don't see why the module isn't just in there.

I would also suggest maybe adding FFI as a built-in extension, it's an excellent replacement for Win32API, allowing you to load in foreign C functions off of shared libraries, it also works on all platforms.

I've actually used FFI by itself and wrote my own Zlib module with it, so it's a really powerful extension.

**Comment by cremno** [comment]
There's also `--with-static-linked-ext`, but it's weird and I don't know if it works on Windows/with MinGW(-w64).

**Comment by Ancurio** [comment]
> There's also --with-static-linked-ext, but it's weird and I don't know if it works on Windows/with MinGW(-w64).

I tried all possible configure switch combinations mentioning extensions and none of them worked.

**Comment by ntzrmtthihu777** [comment]
I think I had that working on my computer... though adding zlib.c into mkxp is a very simple thing.

**Comment by PabloNeirotti** [comment]
Zlib is still not in the pre compiled Windows binary, is it?

I think I am having issues because of it. I definitely know of one Script I had to disable entirely because it couldn't find the "Zlib" module.

Would love a clarification on this. Thank you!

**Comment by Ancurio** [comment]
@PabloNeirotti Ye sorry about that. The Windows build is pretty far behind precisely because I haven't managed to compile it with zlib support yet.

**Comment by PabloNeirotti** [comment]
Ah I see. Thank you! :D

**Comment by Ancurio** [comment]
@PabloNeirotti I have uploaded a fresh mingw32 build with Zlib enabled.
