### ISSUE TITLE
tilemapvx.vert on Ubuntu 14.04 with Nouveau

### ISSUE THREAD

**Issue by Daverball** [Ancurio/mkxp#88]
http://i.imgur.com/5p7zLxA.jpg
Someone that tested a build for me sent me this screenshot, he was basically running a vanilla Ubuntu install with nouveau from what I can tell.

The only point of failure that would make sense to me for this would be something to do with the tilemapvx.vert shader.

I did however compile this build of mkxp myself, so possibly with different GL headers, so it is a possibility I suppose that is part of the problem.

**Comment by Daverball** [comment]
Actually, I just noticed the line `gl_Position = projMat * vec4(position + translation, 0, 1);`

Shouldn't it be 0.0 and 1.0?

**Comment by Ancurio** [comment]
Please have him/her run [this program](https://www.dropbox.com/s/6ooegpn5nl2mxp2/gl_shader_cond.tar.xz) and send you a screenshot. This is for 64bit.

> Actually, I just noticed the line gl_Position = projMat * vec4(position + translation, 0, 1);

You're probably right, not sure why Mesa drivers didn't pick up on that, they're usually very stingy with implicit conversions.

**Comment by Daverball** [comment]
http://i.imgur.com/nTrhWsv.png

**Comment by Ancurio** [comment]
Yeah, driver bug as expected. Unupgraded noveau on Ubuntu 12.04 has that problem unfortunately.

**Comment by Daverball** [comment]
alright, sweet. good to know.
