### ISSUE TITLE
Commission Ancuiro Help?

### ISSUE THREAD

**Issue by JustinCuff** [Ancurio/mkxp#90]
Hello Ancurio, I have been following some of the success with games like LISA ad their current port(s) to mac and linux. I need help with the same ports, but for VXAce. Would you take a look at the
![ms_cover-400-x-400](https://cloud.githubusercontent.com/assets/10532358/5740402/f9f7ff8e-9bb7-11e4-8856-ae04ba6afe00.gif)

 demo for me? 

The Meridian Shard has been greenlit and I would like to have a port for all users. Will work out a commission for you if need be. You can also reach me via email: 

justin AT ultimatefantasystudio.com

Thank you in advance!

**Comment by Ancurio** [comment]
Hello, is there a publicly available demo I can take a look at?

**Comment by JustinCuff** [comment]
Yes, thank you for your response! Here it is:

https://www.kickstarter.com/projects/themeridianshard/the-meridian-shard-rpg-an-indie-game/posts/1103255

Just scroll down a few paragraphs. Thank you for your time.

**Comment by JustinCuff** [comment]
Oops! I forgot it's a basic encryption. I'm sure that's not a problem for you, but may be an inconvenience. I'll upload an open version to mediafire now. Please stand by...

**Comment by Ancurio** [comment]
If it's just the RPG Maker builtin encryption then it's no problem I can unpack it easily.

**Comment by JustinCuff** [comment]
That's what I figured. Thank you Ancurio!

**Comment by Ancurio** [comment]
Ya no problem.

How much will the final game differ from the demo, script wise? Right now, I don't see any Windows-specific parts inside the scripts, and mkxp just runs the game as-is without any modifications on my part, so it should be very easy to provide Linux and OSX versions of it.

**Comment by JustinCuff** [comment]
Fantastic. There should be no further changes to the scripts with the exception of this: http://rpgmakersource.com/ourproducts/effectus/

But I don't see it changing much scriptwise, as it's already running smoothly in my tests today with all the current scripts as is. You can email me with specifics regarding compensation in the event that you are able to get this ported when it's ready. Thank you Jonas!

email: jcuffs@gmail.com

**Comment by Ancurio** [comment]
I see. About Effectus, it doesn't say anywhere how it works (might be using native code for higher performance) so I'll try and ask them just in case.

I'll also close this so it doesn't show up in the issue list, but feel free to continue posting here.

**Comment by JustinCuff** [comment]
Thank you for doing that. Shall we continue correspondence via email from now on? I'll send you the updated demo files so you can have a look.

**Comment by Ancurio** [comment]
Yeah sure.
