### ISSUE TITLE
Sprite not draw at all rather than being partially drawn.

### ISSUE THREAD

**Issue by tarceri** [Ancurio/mkxp#94]
Hello,

I'm using the latest prebuilt binary for Linux from Jan 2015 and also the Win32 wrapper script you made along with the Super Simple Mouse script. I have another script that enables a container to be setup for when to display the cursor.

Under RPGMaker XP when the cursor hits the right and bottom edges of this container the right or bottom parts of the cursor (sprite) don't get drawn because they are outside the container just like when you move the mouse to the right and bottom of you desktop. However under MKXP once any part of the sprite passes the boundary the whole sprite stops being drawn. 

I hope that makes sense. And sorry to spam you about this (also messaged you on reddit yesterday) but thought this was a better place to post it. 

You can find a demo here: http://www.itsqueeze.com/wp-content/uploads/2015/02/Custom_Mouse_System.tar.gz 

And thanks for all your hard work on MKXP.

**Comment by Ancurio** [comment]
Thanks for the report tarceri, I have found the issue and will push a new build soon.

**Comment by Ancurio** [comment]
Please test with this: http://ancurio.bplaced.net/mkxp/generic/mkxp-20150204.tar.xz

Also a tip: You can keep the win32 wrapper as a separate file outside the script database, and then use `preloadScript=<script_name.rb>` in your `mkxp.conf`; this way the game can still be run on Windows.

**Comment by tarceri** [comment]
It's working great now thanks.

Also thanks for the pre load script tip that is much much better.
