### ISSUE TITLE
Can't access event comments from script

### ISSUE THREAD

**Issue by tarceri** [Ancurio/mkxp#96]
The super simple mouse script uses comments in events as a way to trigger mouse over effects. It seems like MKXP isn't allowing these comments to be accessed.

In the attached demo moving the mouse over the events should be triggering mouse over effects. The code is in the Mouse 2 script in update_event_cursors.

  # Get Mouse Position
  x, y = *Mouse.grid

  # Gets Mouse Event
  event = $game_map.event_at(x, y)

    # If Non-Nil Event or not over map HUD
    unless event.nil? 
      # If Not Erased or Nil List
      if event.list != nil && event.erased == false && event.list[0].code == 108
        # Get the comment on the first line
        icon = event.list[0].parameters 
        icon = icon.to_s

I'm assuming code 108 means its a comment.

I haven't looked at the MKXP code as I'm not sure where to start looking but I suspect maybe MKXP isn't storing comments at all as it assumes they won't be useful.

http://www.itsqueeze.com/wp-content/uploads/2015/02/Custom_Mouse_System.tar.gz

**Comment by Ancurio** [comment]
Please try with this script preloaded: http://pastebin.com/DZXYyN21

**Comment by tarceri** [comment]
Thats causing the win32 wrapper script to fail on this line

MKXP.puts("[#{@dll}:#{@func}] #{args.to_s}") if !@call

**Comment by Ancurio** [comment]
Delete that line.

**Comment by tarceri** [comment]
Ok work perfect now thanks.

I take it MKXP.puts("[#{@dll}:#{@func}] #{args.to_s}") if !@call is obsolete?

And the script you gave me works around some kind of ruby compatibility thing?

**Comment by Ancurio** [comment]
> I take it MKXP.puts("[#{@dll}:#{@func}] #{args.to_s}") if !@call is obsolete?

The line is not obsolete, it prints the first time usage of WIn32API (an interface to call into native code), but it's probably not useful to you so it's easier to remove it. If you need it, the way to make it work is to replace `args.to_s` with `args.inspect`.

> And the script you gave me works around some kind of ruby compatibility thing?

Yeah it emulates a few things that were in Ruby 1.8 but removed in 1.9. A ton of scripts in the wild have bugs masked by old Ruby behavior.

**Comment by tarceri** [comment]
Ok, Thanks and sorry about the false alarm. Google gave me the answer too, I'll be more mindful of this type of thing before reporting bugs in future :)

"In 1.8 that is equivalent to calling join, in 1.9 it is equivalent to calling inspect.
To get the behavior you want in both 1.8 and 1.9, call join instead of to_s"

**Comment by Ancurio** [comment]
Don't worry about it, I immediately knew what the issue was because I've fixed it in this same mouse script in about 3 or 4 different games already, but it's not that easy to debug if you don't know what to look for.
