### ISSUE TITLE
Fullscreen Issue (Windows)

### ISSUE THREAD

**Issue by RyanBram** [Ancurio/mkxp#98]
Hi, Jonas,
Thanks for trying to help me. but before you go too far by compiling Windows build for me, I found this issue. It will happen if I am trying to resize the window or make it fullscreen.

![mkxp](https://cloud.githubusercontent.com/assets/4508389/6096622/42b9d1c8-afce-11e4-8bc3-2701b0827a1f.png)

I think it is better for you to fix it first, so I will not disturb you with another bug report. ;)

Thank you very much.

**Comment by Ancurio** [comment]
What is your OS and graphics card? When did you update your graphics drivers last?

**Comment by RyanBram** [comment]
I updated my driver last in 2013 and the following is the summary of my system generated by Speccy and GPU-Z:

```
		Operating System
			Windows 7 Ultimate 64-bit
		CPU
			Intel Core i3 2350M @ 2.30GHz	66 °C
			Sandy Bridge 32nm Technology
		RAM
			6.00GB Dual-Channel DDR3 @ 664MHz (9-9-9-24)
		Motherboard
			Hewlett-Packard 166D (CPU1)	71 °C
		Graphics
			Generic PnP Monitor (1366x768@60Hz)
			Intel HD Graphics Family (HP)
		Storage
			465GB Western Digital WDC WD5000BPKT-24PK4T0 ATA Device (SATA)	48 °C
		Optical Drives
			hp DVDRAM GT50N ATA Device
			ELBY CLONEDRIVE SCSI CdRom Device
		Audio
			IDT High Definition Audio CODEC
```
![gpuz](https://cloud.githubusercontent.com/assets/4508389/6096778/3d1a841c-afd6-11e4-8979-b5b2b389732e.gif)

**Comment by Ancurio** [comment]
Ah yes, this seems about right, Intel is notorious for very bad drivers :) Have you tried downloading the latest graphics drivers?

**Comment by RyanBram** [comment]
The problem fixed after installing last update. I played many games and emulator, but never found the problem like this.
Sigh, how do I never think about it before?

Thanks for helping. (^_^)
